INSERT INTO MACHINE(MID,MNAME,MLANG) VALUES(19, 'Manoj','sdsd');
INSERT INTO MACHINE(MID,MNAME,MLANG) VALUES(20, 'Arun','java');
INSERT INTO MACHINE(MID,MNAME,MLANG) VALUES(21, 'Nissar','orient');
INSERT INTO MACHINE(MID,MNAME,MLANG) VALUES(23, 'Geetha','mongodb');
INSERT INTO MACHINE(MID,MNAME,MLANG) VALUES(22, 'Swetha','spring');
INSERT INTO MACHINE(MID,MNAME,MLANG) VALUES(25, 'Kumar','java');